### PR TITLE
6pm-c-svpa tutor assignment

### PR DESCRIPTION
**Pull request by sethvanb**
This PR is the create and read operations for tutor assignments. For the front end it adds a page to view tutorAssignments and a page to create new tutor assignments as well as components for the display table and submission form and lastly services to help send the creation form to the back end. I also added in code that Bryne Terce(sorry if this is spelled incorrectly) wrote that helps convert the format of quarters for courses. For the backend I added a controller for tutor assignment that has a get and a put and I added a tutor assignment repository. I added a couple more specific gets to course controller and a couple different finds to the course repository.

### CODE REVIEW

**Comment by pconrad** [comment]
@sethvanb  you need to get this green on CI before it can be merged.  If you need help with that, please:
* ask in section today
* ask during office hours
* ask on Slack

**Review by pconrad — APPROVED** [review]
LGTM.   40 points

**Review by parthatre — APPROVED** [review]
Looks good to me.

**Comment by pconrad** [comment]
40 points for this!  Nice job

**Pull request merged**
