### PR TITLE
6pm b course tutor history frontend

### PR DESCRIPTION
**Pull request by to-mmy**
In this PR issue #30 is addressed where we add the front end to allow a user to search a course number (Ex. CMPSC 156, etc), then get the history of tutors who have been assigned to the course.

### CODE REVIEW

**Comment by pconrad** [comment]
Description: "In this PR is the frontend for issue #30" is insufficient.

Title: "course tutor history frontend" is helpful, but please put the user story into the PR description.

Also: there are merge conflicts that need to be resolved as of right now

**Review by TravisKoski — DISMISSED** [review]
Overall goodjob, staff ready to review

**Review by matthewwong212 — APPROVED** [review]
Fixed merge conflicts with main

**Review by mara-downing — APPROVED** [review]
LGTM

**Review by TravisKoski — COMMENTED** [review]
Looks good

**Pull request merged**
