### PR TITLE
6pm-d CourseName to CourseNumber, Issue #23

### PR DESCRIPTION
**Pull request by alejandrodiera**
This Pull Request fixes Issue #23

----

**User Story**
As a user, the course number field is labeled properly so that I can find proper office hours.

**Acceptance Criteria**
Each course should have its number displayed.

**Implementation**
Front end:
Re-label column to display proper names. (i.e. course number)
Change variable name from Course Name to Course Number.

Back end:
Change variable name from Course Name to Course Number.

Testing:
Front end tests pass and there is adequate coverage
Back end tests pass and there is adequate coverage

----

Changed attribute 'String name' in Class object to 'String number'. Every reference of Course name was replaced by Course number. Made edits to front and back end tests to account for this.

### CODE REVIEW

**Comment by scottpchow23** [comment]
Add 10 points for moving Course into the entity folder.

**Comment by alejandrodiera** [comment]
Only changed Course Name to Course Number.
Tried to move Course.java to entities directory but was getting weird errors with rebranch so I left it in models directory.

**Review by lukelewis66 — APPROVED** [review]
Changing name to number looks straight forward. Coverage is still 100% so I'd say this is good to go. Though I am a bit worried as to why there are so many lines deleted (DemoApplicationTests.java, TutorAssignmentControllerTests.java, TutorAssignmentController.java). Mind explaining why these files are deleted?

**Comment by alejandrodiera** [comment]
> Changing name to number looks straight forward. Coverage is still 100% so I'd say this is good to go. Though I am a bit worried as to why there are so many lines deleted (DemoApplicationTests.java, TutorAssignmentControllerTests.java, TutorAssignmentController.java). Mind explaining why these files are deleted?

DemoApplicationTest.java was removed by Scott when he and I were working together to figure out why the CI had more tests then locally and traced it back to that file, we added configurations to pom.xml for it to be ignored so we just decided to delete it since it wasn't being used. 
-- This is the end of my current issue (Course Name to Course Number)

The TutorAssignmentController files were added on after I re-branched main because I was attempting to work on moving the Course entity to the entities folder from the current modules but was receiving an interesting error so I just reverted back to the original issue and removed those added files.

**Comment by alejandrodiera** [comment]
Changed the element 'name' in the Course object to 'number'. Changed all instances where a Course object was defined to accommodate this change and in all parameters as well.

**Comment by alejandrodiera** [comment]
**User Story**
As a user, the course number field is labeled properly so that I can find proper office hours.

**Acceptance Criteria**
Each course should have its number displayed.

**Implementation**
Front end:
Re-label column to display proper names. (i.e. course number)
Change variable name from Course Name to Course Number.

Back end:
Change variable name from Course Name to Course Number.

Testing:
 Front end tests pass and there is adequate coverage
 Back end tests pass and there is adequate coverage

**Comment by alejandrodiera** [comment]
The file 'DemoApplicationTests.java' was deleted because Scott and I added a <exclude> tag for the file in a jacoco configuration inside of pom.xml. It was deleted because the tests were not even running do there was no need for the file.

**Review by lukelewis66 — DISMISSED** [review]
Looks good!

**Comment by alejandrodiera** [comment]
> Changing name to number looks straight forward. Coverage is still 100% so I'd say this is good to go. Though I am a bit worried as to why there are so many lines deleted (DemoApplicationTests.java, TutorAssignmentControllerTests.java, TutorAssignmentController.java). Mind explaining why these files are deleted?

**TutorAssignmentControllerTests.java and TutorAssignmentController.java re-added with the most recent rebase.

**DemoApplicationTests.java was deleted because Scott and I added a tag for the file in a jacoco configuration inside of pom.xml. It was deleted because the tests were not even running do there was no need for the file.

**Comment by alejandrodiera** [comment]
> Looks good!

Thanks for taking the time to look through and review!

**Comment by alejandrodiera** [comment]
**Latest Updated Branch**

Completed rebase and merge conflicts.

Waiting on reviews.

**Comment by alejandrodiera** [comment]
**Latest Updated Branch**

Completed rebase and merge conflicts.

Waiting on reviews.

**Review by ssmith563 — DISMISSED** [review]
Looks good to me!

**Pull request closed without merging**
